### ISSUE TITLE
MockDirectory.SetCreationTime throws NullReferenceException

### ISSUE THREAD

**Issue by JamesLauth** [System-IO-Abstractions/System.IO.Abstractions#223]
Attempting to set the creation date of a mock directory results in a null reference exception. Here is an NUnit test that demonstrates the issue:
```csharp
[TestCase(true)]
[TestCase(false)]
public void TestDirectorySetCreationTime(bool realFileSystem)
{
  const string PATH = @"C:\test123";
  IFileSystem fs = realFileSystem ?
    (IFileSystem) new FileSystem() :
    (IFileSystem) new MockFileSystem();
  fs.Directory.CreateDirectory(PATH);
  fs.Directory.SetCreationTime(PATH, DateTime.Now);  // throws if fs is a MockFileSystem
  fs.Directory.Delete(PATH);
}
```
More information about the exception:
```
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=System.IO.Abstractions.TestingHelpers
  StackTrace:
       at System.IO.Abstractions.TestingHelpers.MockFile.SetCreationTime(String path, DateTime creationTime)
       at System.IO.Abstractions.TestingHelpers.MockDirectory.SetCreationTime(String path, DateTime creationTime)
  InnerException:
```
I am new to GitHub (and Git itself), but will attempt a fix.

**Comment by JamesLauth** [comment]
The source of the null value is the MockFileSystem.GetFileWithoutFixingPath method:
```csharp
private MockFileData GetFileWithoutFixingPath(string path)
{
    lock (files)
    {
        MockFileData result;
        files.TryGetValue(path, out result);
        return result;
    }
}
```
The call `files.TryGetValue(path, out result)` does not find the path C:\test123 because it doesn't end with a backslash. Consequently the return value is null, which results in a `NullReferenceException` later in the code.

The issue can be fixed with the following 2-line change to `GetFileWithoutFixingPath`:
```csharp
private MockFileData GetFileWithoutFixingPath(string path)
{
    lock (files)
    {
        MockFileData result;
        files.TryGetValue(path, out result);
        if (result == null)
            files.TryGetValue(path + @"\", out result);
        return result;
    }
}
```
All unit test still pass, including the one I added for this issue. However, it appears the code generally expects a trailing backslash on directories, and I am leery of short-circuiting this behavior. Any thoughts or comments about the proposed change would be appreciated.

Below is the additional unit test:
```csharp
[Test]
public void MockDirectory_SetCreationTime_ShouldNotThrowWithoutTrailingBackslash()
{
    const string PATH = @"C:\NoTrailingBackslash";
    MockFileSystem fs = new MockFileSystem();
    fs.Directory.CreateDirectory(PATH);
    fs.Directory.SetCreationTime(PATH, DateTime.Now);
    fs.Directory.Delete(PATH);
}
```
