### ISSUE TITLE
TestingHelpers not usable on non-Windows platforms

### ISSUE THREAD

**Issue by fgreinacher** [System-IO-Abstractions/System.IO.Abstractions#272]
The TestingHelpers package is currently not usable on non-Windows platforms as even the simplest operations are failing, e.g.:

```
Error Message:
 System.PlatformNotSupportedException : Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.
Stack Trace:
   at System.Security.AccessControl.ObjectSecurity..ctor()
   at System.Security.AccessControl.CommonObjectSecurity..ctor(Boolean isContainer)
   at System.Security.AccessControl.NativeObjectSecurity..ctor(Boolean isContainer, ResourceType resourceType)
   at System.Security.AccessControl.DirectorySecurity..ctor()
   at System.IO.Abstractions.TestingHelpers.MockDirectoryData..ctor()
   at System.IO.Abstractions.TestingHelpers.MockFileSystem.AddDirectory(String path)
```

**Comment by skolima** [comment]
related: #252

**Comment by tathamoddie** [comment]
Travis CI build now in place so that we can see what all the gaps are, and avid introducing new ones in new pull requests: https://travis-ci.org/System-IO-Abstractions/System.IO.Abstractions

**Comment by fgreinacher** [comment]
Thanks
