### ISSUE TITLE
Version 2.1.0.233 and onwards seem to break files with binary content

### ISSUE THREAD

**Issue by potomato** [System-IO-Abstractions/System.IO.Abstractions#375]
I've been using SIAT in unit tests with mock files containing binary content for a while (and loving it). 
Binary content used to be fine but a recent update is causing my units to fail because it seems now this content is attempting to be read as Unicode.

The following code works fine in v232, but throws exception in subsequent versions:
`var binaryData = new byte[] { 0xC0 };
            var fs = new MockFileSystem(new Dictionary<string, MockFileData>() { { @"c:\source\file.jpg", new MockFileData(binaryData) } } );
            fs.AddDirectory(@"c:\source");
            fs.AddDirectory(@"c:\dest");
            fs.File.Copy(@"c:\source\file.jpg", @"c:\dest\file.jpg");`

Is this expected behaviour? I can change my tests to ensure the binary content can be read as Unicode - but there's a MockFileData taking byte[], and it seems reasonable for a mock file system to be able to handle binary files. I can help knock up better tests if that would help.

Exception is:
System.Text.DecoderFallbackException
  HResult=0x80070057
  Message=Unable to translate bytes [C0] at index 0 from specified code page to Unicode.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Text.DecoderExceptionFallbackBuffer.Throw(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderExceptionFallbackBuffer.Fallback(Byte[] bytesUnknown, Int32 index)
   at System.Text.DecoderFallbackBuffer.InternalFallback(Byte[] bytes, Byte* pBytes, Char*& chars)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.Abstractions.TestingHelpers.MockFile.ReadAllBytes(Byte[] contents, Encoding encoding)
   at System.IO.Abstractions.TestingHelpers.MockFileData..ctor(MockFileData template)
   at System.IO.Abstractions.TestingHelpers.MockFile.Copy(String sourceFileName, String destFileName, Boolean overwrite)

**Comment by erenes** [comment]
Reproduced using the following testcase: 
```      
      var binaryData = new byte[] { 0xC0 };
      var mockFile1 = new MockFileData(binaryData);
      var mockFile2 = new MockFileData(mockFile1);
```

It looks like the TextContents are copied in this constructor, rather than the binary contents. Looks like it was introduced with PR #354 

To make sure that the issue that fixes is not reintroduced, the MockFileData constructor taking the MockFileData as parameter, should use Array.Clone on the contents, rather than copying the TextContents.

**Comment by jbaehr** [comment]
Could you please push a new release of the 2.1.0 line to nuget.org? The current latest stable 2.1.0.256 was released four days *before* this critical fix ;-)

**Comment by fgreinacher** [comment]
Our next release will be 3.0 - I’ll try to deploy within the next days.

**Comment by fgreinacher** [comment]
@jbaehr Done -> https://www.nuget.org/packages/System.IO.Abstractions/3.0.2
