### ISSUE TITLE
MockFileSystem.AddFilesFromEmbeddedNamespace() method throws ArgumentNullException

### ISSUE THREAD

**Issue by ristogod** [System-IO-Abstractions/System.IO.Abstractions#921]
Given a project named "Test" with a "Files" folder within it, and within that folder there are 5 files included as embeddedResources, when I call the given code, it always throw an exception:

```
System.ArgumentException: 'Value cannot be null. (Parameter 'key')'

   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.IO.Abstractions.TestingHelpers.MockFileSystem.DirectoryExistsWithoutFixingPath(String path)
   at System.IO.Abstractions.TestingHelpers.MockFileSystem.AddFile(String path, MockFileData mockFile)
   at System.IO.Abstractions.TestingHelpers.MockFileSystem.AddFilesFromEmbeddedNamespace(String path, Assembly resourceAssembly, String embeddedRresourcePath)
```

This is how I'm calling the code
``` csharp
MockFileSystem fileSystem = new();
fileSystem.AddFilesFromEmbeddedNamespace(@"\\Test.Files", typeof(MyClass).Assembly, "Test.Files" );
```

**Comment by fgreinacher** [comment]
> I couldn't reproduce your problem from the description alone. Could you provide an example project to reproduce the behaviour, or check if you can adapt the test case so that it fails?

@ristogod Could you please help us reproduce this?
